linter:
  rules:
    - camel_case_types
    - library_names
    - file_names
    - library_prefixes
    - non_constant_identifier_names
    - directives_ordering
    - unnecessary_lambdas
    - prefer_expression_function_bodies